FROM node:alpine as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build
LABEL authors="dimitriaigle"

FROM nginx:latest
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
